library(RGeostats)
rain.csv <- read.csv(file="C:\\Users\\jeff_dsktp\\Documents\\precipitation_processing\\20130702.csv", head=TRUE, sep=",")
rain.db <- db.create(rain.csv,ndim=2,autoname=F,flag.grid=F)
rain.db <- db.locate(rain.db, "datetime")
rain.db <- db.locate(rain.db, "precip_mm","z")
data.vario <- vario.calc(rain.db,lag=1000,nlag=20)
plot(data.vario,npairdw=TRUE,npairpt=1)
data.4dir.vario <- vario.calc(rain.db,lag=1000,nlag=20,dir=c(0,45,90,135))
plot(data.4dir.vario,title="Directional variograms")
data.model <- model.auto(data.vario,struct=c("Spherical","Exponential"),title="Modelling omni-directional variogram")
jpeg('variogram.jpg')
plot(data.vario,npairdw=TRUE,npairpt=1)
plot(data.model, add=TRUE)
dev.off()
unique.neigh = neigh.init(ndim = 2, type = 0)
moving.neigh = neigh.init(ndim = 2, type = 2, nmini = 1, nmaxi = 8, nsect = 8, nsmax = 2, flag.sector=TRUE, dmax = 10000)
rain.db <- xvalid(rain.db, data.model, moving.neigh)
hist(db.extract(rain.db,"Xvalid.precip_mm.esterr"), nclass=30, main="Histogram of precip error" , xlab="Cross-validation error", col="blue")
grid.db <- db.grid.init(rain.db,nodes=c(100,100))
rain.db <- db.locate(rain.db,seq(6,7))
rain.db <- db.locate(rain.db,"precip_mm","z")
grid.db <- kriging(rain.db,grid.db,data.model,unique.neigh,radix="ku")
ramp <- colorRampPalette(c("white","blue"))
color.bar <- function(lut, min, max=-min, nticks=11, ticks=seq(min, max, len=nticks), title='') {
    scale = (length(lut)-1)/(max-min)
    #dev.new(width=1.75, height=5)
    plot(c(0,10), c(min,max), type='n', bty='n', xaxt='n', xlab='', yaxt='n', ylab='Precipitation_mm', main=title, add=T)
    axis(2, ticks, las=1)
    for (i in 1:(length(lut)-1)) {
     y = (i-1)/scale + min
     rect(0,y,10,y+1/scale, col=lut[i], border=NA)
    }
}
jpeg('kriging.jpg')
plot(grid.db, name.image="ku.precip_mm.estim", col=ramp(100), title="Estimation of precipitation for 20130703")
plot(rain.db, pch=21, bg=1, add=T)
par(fig=c(0.8,1,0,1),new=T)
color.bar(ramp(50),1,50)
dev.off()

